import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

test('catalog fixture contains the builder surface', async () => {
  const index = await readFile(new URL('../index.html', import.meta.url), 'utf8');
  assert.match(index, /version-disclaimer/);
  assert.match(index, /official Betaflight/);
  assert.match(index, /kidce\.github\.io\/KidCe-Configurator/);
  assert.match(index, /id="target"[^>]+list="targetList"/);
  const catalog = JSON.parse(await readFile(new URL('../data/catalog.json', import.meta.url)));
  assert.equal(catalog.mode, 'fixture');
  assert.ok(catalog.targets.some((target) => target.target === 'KAKUTEH7'));
  assert.ok(catalog.targets.some((target) => target.target === 'HDZERO_HALO'));
  assert.ok(catalog.targets.some((target) => target.target === 'MAMBAF722_2022A'));
  assert.ok(catalog.targets.some((target) => target.target === 'HGLRCF722MINI'));
  const kaackLine = catalog.firmwareLines.find((line) => line.id === 'kaack');
  const betaflightLine = catalog.firmwareLines.find((line) => line.id === 'betaflight');
  assert.ok(kaackLine.releases.some((release) => release.label === 'KAACK 4.5.3 / V19' && release.ref === 'KAACK-4.5.0'));
  assert.ok(betaflightLine.releases.some((release) => release.label === 'Betaflight 4.5.3' && release.ref === '4.5.3'));
  assert.ok(betaflightLine.targets.length < 10);
  assert.ok(catalog.options.osdProtocols.some((option) => option.value.includes('USE_OSD_HD')));
});

test('workflow validates user-controlled flags before make', async () => {
  const workflow = await readFile(new URL('../.github/workflows/build-firmware.yml', import.meta.url), 'utf8');
  assert.match(workflow, /Invalid build flag/);
  assert.match(workflow, /make configs/);
  assert.match(workflow, /make arm_sdk_install/);
  assert.match(workflow, /submodules: recursive/);
  assert.match(workflow, /picotool_install/);
  assert.match(workflow, /build_command=\(make -j7 "\$\{target\}"/);
  assert.match(workflow, /make uf2 TARGET/);
  assert.match(workflow, /src\/platform src\/main/);
  assert.match(workflow, /src\/config\/configs -type f -path/);
  assert.match(workflow, /CONFIG="\$\{target\}"/);
  assert.match(workflow, /config_ref/);
  assert.match(workflow, /compatible pinned config ref/);
  assert.match(workflow, /immutable source commit/);
  assert.match(workflow, /8cd44381217948c0b2b5087f12e17dde15d6a25c/);
  assert.match(workflow, /Expected exactly one target-specific HEX artifact/);
  assert.match(workflow, /HEX artifact does not match the target-specific ELF/);
  assert.match(workflow, /valid Intel HEX end-of-file record/);
  assert.match(workflow, /arm-none-eabi-objcopy/);
  assert.match(workflow, /-size \+0c/);
  assert.match(workflow, /limonspb\/betaflight/);
  assert.match(workflow, /upload-artifact@v4/);
  assert.match(workflow, /FIRMWARE_REPOSITORY/);
  assert.match(workflow, /approved KAACK fork/);
  assert.match(workflow, /firmware_stem=/);
  assert.match(workflow, /version_slug/);
  assert.match(workflow, /version_slug_value="K\$\{version_slug_value#KAACK-\}"/);
  assert.match(workflow, /firmware_stem="\$\(slug "\$\{REQUEST_TARGET\}"\)_\$\(version_slug\)_/);
  assert.match(workflow, /firmware_line/);
  assert.match(workflow, /betaflight\/betaflight/);
  assert.match(workflow, /limonspb\/betaflight/);
  assert.match(workflow, /DIGIOSD/);
  assert.match(workflow, /content-disposition/);
  assert.match(workflow, /firmwareFileName/);
  assert.match(workflow, /-DBUILD_KEY=\$\{build_key\} -DRELEASE_NAME=\$\{release_name\}/);
  assert.doesNotMatch(workflow, /BUILD_KEY=\\\\\\"/);
  assert.match(workflow, /USE_SERIALRX/);
  assert.match(workflow, /USE_TELEMETRY/);
  assert.doesNotMatch(workflow, /DEFAULT_RX_FEATURE/);
});

test('worker keeps GitHub credentials server-side', async () => {
  const worker = await readFile(new URL('../worker/index.js', import.meta.url), 'utf8');
  assert.match(worker, /GITHUB_TOKEN/);
  assert.match(worker, /headers\.authorization = `Bearer \$\{env\.GITHUB_TOKEN\}`/);
  assert.match(worker, /validateAgainstCatalog/);
  assert.match(worker, /downloadFirmware/);
  assert.match(worker, /downloadFormat/);
  assert.match(worker, /Live builder unavailable/);
  assert.doesNotMatch(worker, /mode: "demo"|Demo mode/);
  assert.match(worker, /object\.httpMetadata\?\.contentDisposition/);
  assert.match(worker, /source_ref/);
  assert.match(worker, /src.*platform/);
  assert.match(worker, /src.*main/);
  assert.match(worker, /src.*config/);
  assert.match(worker, /configs.*\[\^\/\].*config/);
  assert.match(worker, /gitTree/);
  assert.match(worker, /configRef/);
  assert.match(worker, /cacheKey: await cacheKey\(\{ \.\.\.recipe, sourceRef, configRef \}\)/);
  assert.match(worker, /officialConfigRefFor/);
  assert.match(worker, /92c695af8a2756d75152b54959de28d48fc25cf7/);
  assert.match(worker, /supportsConfigBuild/);
  assert.match(worker, /releases before 4\.5/);
  assert.match(worker, /optionsForRelease/);
  assert.match(worker, /USE_LED_STRIP_64/);
  assert.match(worker, /USE_SDCARD/);
  assert.match(worker, /\^\[A-Z0-9_-\]\+\$/);
  assert.doesNotMatch(await readFile(new URL('../app.js', import.meta.url), 'utf8'), /GITHUB_TOKEN/);
});

test('builder remembers general options and applies racing defaults', async () => {
  const app = await readFile(new URL('../app.js', import.meta.url), 'utf8');
  const flags = await readFile(new URL('../shared/build-flags.js', import.meta.url), 'utf8');
  const index = await readFile(new URL('../index.html', import.meta.url), 'utf8');
  assert.match(app, /kaack-cloud-builder\.general-options/);
  assert.match(app, /USE_SERIALRX_CRSF/);
  assert.match(flags, /USE_TELEMETRY/);
  assert.match(flags, /USE_TELEMETRY_CRSF/);
  assert.match(app, /USE_DSHOT/);
  assert.match(app, /USE_OSD_HD/);
  assert.match(app, /firmwareLines/);
  assert.match(app, /firmware=\$\{encodeURIComponent\(state\.firmwareLine\)\}/);
  assert.match(app, /not the same as Betaflight 4\.5\.3/);
  assert.match(app, /older Betaflight 4\.5 line/);
  assert.match(app, /all fixes from official Betaflight 4\.5\.3/);
  assert.doesNotMatch(app, /data\/catalog\.json/);
  assert.doesNotMatch(app, /demoBuild|createDemoDownload|NOT FLASHABLE/);
  assert.match(app, /Live builder unavailable/);
  assert.match(app, /Download ZIP artifact/);
  assert.match(app, /DEFAULT_API_BASE/);
  assert.match(app, /targetList/);
  assert.match(app, /racingOptions/);
  assert.match(app, /additionalOptions/);
  assert.match(app, /RACING_DEFAULT_FLAGS/);
  assert.match(index, /Serial RX via UART/);
  assert.match(index, /report_cell_voltage/);
});
